# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Faz o checkout do código
    - uses: actions/checkout@v4

    # Configura o JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Verifica a estrutura de diretórios para debugging (opcional)
    - name: Debug directory structure
      run: |
        pwd
        ls -R

    # Navega até o diretório onde o build.xml está localizado e executa o Ant
    - name: Build with Ant
      run: |
        cd WebApplication # Altere o caminho conforme necessário
        ant -noinput -buildfile build.xml
